### ISSUE TITLE
Explanation of Todo (+) in TASK MANAGEMENT section

### ISSUE THREAD

**Issue by kaorahi** [Emacs101/howm-manual#4]
I noticed that the explanation of Todo (+) in TASK MANAGEMENT section might be misleading (kaorahi/howm#3).

> Todo is at the bottom of the list. It starts to gradually float to the top of the list seven days before the due date.

While this description is technically accurate, the floating before the specified date is so slight that it is unnoticed practically. The noticeable shift actually starts from the specified date itself.

How about simply saying like "gradually float to the top of the list from the specified date"?

**Comment by Emacs101** [comment]
> How about simply saying like "gradually float to the top of the list from the specified date"?

Thank you for pointing out that there is ambiguity. I guess I would need to correct not only this phrase. :) 

Can you help me out with this? 

Is this passage correct?

> The todo gradually starts to float to the surface of the list 7 days before the date. If you want it to start surfacing earlier, increase the number, for example: [2023-06-25]+14

**Comment by kaorahi** [comment]
Here's my proposed draft. Please feel free to adapt, cut, or improve upon it as you see fit, including fixing any awkward English.

By the way, is the term "reminder" misleading? I originally chose it as the English name, but I'm now questioning whether "memo" or "note" might be more fitting. I'd appreciate hearing any thoughts.

I never actually set future dates for the "reminder". I just use it with today's date for random things I hope to do/study/read/... and let most of them sink since obviously, the sum of them exceeds my capacity. For special items, I use `[2023-06-xx]-99` to keep them visible longer.

========================

The scheduled event appears in the list seven days before the appointed date and ...(snip)... If you want it to appear earlier, increase the period number, for example: `[2023-06-xx]@14` (14 days before).

The deadline is at the bottom of the list. Seven days before the date, it instantly floats up and stays at the very top even after the deadline. If you want it to start surfacing earlier, increase the period number, for example: `[2023-06-xx]!14` (14 days before).

Todo stays at the bottom of the list until the appointed date. After that, it starts to gradually float to the top of the todo list, taking 7 days by default to reach the top. If you prefer a slower ascent, increase the period number, for example: `[2023-06-xx]+14` (14 days to the top).

The reminder stays at the bottom of the list until the appointed date. It appears at the top of the todo list (below any overdue deadlines) on the appointed date and then sinks a little each day, eventually diving to the bottom of the list again. The default descent speed is "1 unit per 1 day". If you want it to sink slower, increase the period number, for example: `[2023-06-xx]-14` (1 unit per 14 days).

The deferred behaves like a reminder. The difference is that resurfacing and diving are cyclical. It will float up over and over again at 30-day intervals. If you want to adjust the interval, modify the period number, for example: `[2023-06-xx]~14` (at 14-day intervals).

**Comment by Emacs101** [comment]
Based on your explanation of the purpose of a “reminder,” the best choice would be a “memo.” However “reminder” works as well, especially since someone could use it to remind their future self about important information.

I have another question about the behavior of +. 

You wrote: 
> If you prefer a slower ascent, increase the period number, for example: [2023-06-xx]+14 (14 days to the top)

If I call it a to-do list – and it is February 16, 2024 – I will receive this:

Fri     -7  [2024-02-23]+40 task #6
Sun   -2  [2024-02-18]+      task #1  
Mon  -3  [2024-02-19]+      task #2  
Tue   -4  [2024-02-20]+      task #3  
Wed -5   [2024-02-21]+      task #4  
Thu  -6   [2024-02-22]+     task #5

The task #6 with append number 40 is currently at the top of the list. 
It still seems that tasks with append numbers ascend to the surface faster than more recent tasks.
However, on February 18, 2024, tasks #1 and #2 will move to the top of the list. 

Perhaps there is some ambiguity regarding what should be considered the bottom and the top of the list?

**Comment by Emacs101** [comment]
Based on your explanation of the purpose of a “reminder,” the best choice would be a “memo.” However “reminder” works as well, especially since someone could use it to remind their future self about important information.

I have another question about the behavior of +. 

You wrote: 
> If you prefer a slower ascent, increase the period number, for example: [2023-06-xx]+14 (14 days to the top)

If I call it a to-do list – and it is February 16, 2024 – I will receive this:

Fri     -7  [2024-02-23]+40 task  №6
Sun   -2  [2024-02-18]+      task №1  
Mon  -3  [2024-02-19]+      task №2  
Tue   -4  [2024-02-20]+      task №3  
Wed -5   [2024-02-21]+      task №4  
Thu  -6   [2024-02-22]+     task №5

The task №6 with +40 is currently at the top of the list. It seems that tasks with numbers after "+" ascend to the surface faster than more immediate tasks.
However, on February 18, 2024, tasks №1 and №2 will move to the top of the list. 

Perhaps there is some ambiguity regarding what should be considered the bottom and the top of the list?

**Comment by kaorahi** [comment]
(Short answer)

`[2024-02-xx]+` means "hide this item until 2024-02-xx". In the present case, all the future items are buried at the "bottom" of the list. The order among these "bottom" items is meaningless.

If this is confusing, you can try `M-x customize-group RET howm-menu-reminder RET` and change "Howm Menu Todo Priority" to "Hide sleeping reminders".

(Long answer)

Each item has a priority value (larger = higher) that is dynamically calculated based on the current date and the item's properties. All the items are sorted by their priorities and the first 50 items are listed in the menu. To show the priority in the menu, use the following code:

```
(setq howm-menu-todo-priority-format "(%8.1f)")
```

In general, you will notice three clusters of priorities. Let's temporarily call the priority values around 77777 "top", around -77777 "bottom", and around 0 "middle". Note that we practically never see the "bottom" items in the menu since it tends to fill up with many "top" and "middle" items over time. So, please don't mind the order among bottom items as it is meaningless.

* `[2024-02-xx]!` "bottom" until this date - 7 days. "top" after this date. "middle" between them.
* `[2024-02-xx]+` "bottom" until this date. Then ascends inside "middle".
* `[2024-02-xx]-` "bottom" until this date. Then descends inside "middle".
* `[2024-02-xx]~` "bottom" until this date. Then oscillates inside "middle".

Illustration of the priorities (inf = 77777 actually)

![priority](https://github.com/Emacs101/howm-manual/assets/38910552/8da4e3a5-fe59-4a5a-b077-826d41dbaa97)

**Comment by Emacs101** [comment]
Thank you so much! This has been incredibly helpful. I realize that I definitely need to make some revisions to the TASK MANAGEMENT section. May I use these cool diagrams of yours? Of course, I will provide proper attribution.

**Comment by kaorahi** [comment]
Sure!

If you want to modify the diagrams, kaorahi/howm@7c88f0b is the source code.
See also kaorahi/howm#4 to simulate the todo list for a specific date.

I'm considering adding visual cues for the "bottom" items, such as gray backgrounds, if I can.
